swagger: '2.0'
info:
    title: Product Catalog Management
    description: This is Swagger UI environment generated for the TMF Product Catalog Management specification
    version: '4'
host: serverRoot
basePath: /tmf-api/productCatalogManagement/v4/
schemes:
    - https
consumes:
    - application/json
produces:
    - application/json
paths:
    /category:
        get:
            operationId: listCategory
            summary: List or find 'Category' objects
            tags:
                - category
            parameters:
                - type: string
                  required: true
                  in: header
                  name: Channel
                  description: Channel
                - type: string
                  required: true
                  in: header
                  name: Profile
                  description: Profile
                - type: string
                  required: true
                  in: header
                  name: Accept-Language
                  description: Category internationalization language
                - type: integer
                  required: false
                  in: query
                  name: offset
                  description: Requested index for start of resources to be provided in response
                - type: integer
                  required: false
                  in: query
                  name: limit
                  description: Requested number of resources to be provided in response
            responses:
                '200':
                    description: Ok
                    schema:
                        items:
                            $ref: '#/definitions/Category'
                        type: array
                '400':
                    description: Bad Request
                    schema:
                        $ref: '#/definitions/Error'
                '500':
                    description: Internal Server Error
                    schema:
                        $ref: '#/definitions/Error'
definitions:
    Category:
        type: object
        description: 'The category resource is used to group product offerings, service and resource candidates in logical containers. Categories can contain other categories and/or product offerings, resource or service candidates.'
        properties:
            id:
                type: string
                description: Unique identifier of the category
            name:
                type: string
                description: Name of the category
            description:
                type: string
                description: Description of the category
            price:
                type: integer
                description: Зкшсу of the category
    Error:
        required:
            - error
            - message
            - error_description
            - requestId
        properties:
            error:
                type: string
                description: A short localized string that describes the error.
            error_description:
                type: string
                description: '(optional) A long localized error description if needed. It can contain precise information about which parameter is missing, or what are the identifier acceptable values.'
            requestId:
                type: string
                description: Request id
            params:
                type: object
                description: (optional) Error params.
